import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { headers } from 'next/headers'
import { type ReactNode } from 'react'
import { cookieToInitialState } from 'wagmi'
import { wagmiConfig } from '@/wagmi';
import '@rainbow-me/rainbowkit/styles.css';
import { Providers } from './providers'
import { ConnectButton } from '@rainbow-me/rainbowkit'
import Header from '@/components/header'
const inter = Inter({ subsets: ['latin'] })



export const metadata: Metadata = {
  title: 'Create Wagmi',
  description: 'Generated by create-wagmi',
}

export default function RootLayout(props: { children: ReactNode }) {
  const initialState = cookieToInitialState(
    wagmiConfig,
    headers().get('cookie'),
  )
  console.log(initialState, 'initialState')
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers initialState={initialState}>
          <Header />
          {props.children}
        </Providers>
      </body>
    </html>
  )
}
